on:
  push:
    tags:
      - 'v*'

name: Release

env:
  CI: 1
  TRAVIS_BUILD_DIR: ${{ github.workspace }}

jobs:
  releases:
    name: Upload build files
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Switch PHP version
        env:
          PHP_VERSION: '5.6'
        run: sudo ln -sf "/usr/bin/php$PHP_VERSION" /etc/alternatives/php
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci && bash travis-ci/bin/prepare.sh
      - name: Build
        run: source travis-ci/bin/deploy/env.sh && bash travis-ci/bin/deploy/create.sh
      - name: Upload
        uses: technote-space/action-gh-release@v2
        with:
          files: release.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: [releases]
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
